const FeaturedListingData = [
  {
    id: 1,
    image: "house1.png",
    status: "For Sale",
    address: "1963 S Crescent Heights Blvd",
    location: "Hills, CA 90210",
    size: "2400 Square Feet",
    parking: "2 Garages",
    bedrooms: "20 Bedrooms",
    bathrooms: "8 Bathrooms",
    ownerName: "Michel Smith",
    lastActivity: "1 days ago",
    amount: "$5,304,000",
  }, {
    id: 2,
    image: "house2.png",
    status: "For Rent",
    address: "302 North Plam Drive",
    location: "Beverly Hills, CA 90210",
    size: "2300 Square Feet",
    parking: "3 Garages",
    bedrooms: "20 Bedrooms",
    bathrooms: "10 Bathrooms",
    ownerName: "Adam Smith",
    lastActivity: "5 days ago",
    amount: "$5,142,000",
  },{
    id: 3,
    image: "house3.png",
    status: "For Sale",
    address: "28 Quaker Road, Manhasset",
    location: "California Hills, CA 90210",
    size: "2020 Square Feet",
    parking: "2 Garages",
    bedrooms: "22 Bedrooms",
    bathrooms: "11 Bathrooms",
    ownerName: "David Lee",
    lastActivity: "5 days ago",
    amount: "$4,784,000",
  },
  {
    id: 4,
    image: "house4.png",
    status: "For Sale",
    address: "Sofi Berryessa 750 King Road",
    location: "Los Angel, CA 90210",
    size: "2350 Square Feet",
    parking: "2 Garages",
    bedrooms: "22 Bedrooms",
    bathrooms: "11 Bathrooms",
    ownerName: "Lee Hue",
    lastActivity: "5 days ago",
    amount: "$3,534,000",
  },
  {
    id: 5,
    image: "house5.png",
    status: "For Rent",
    address: "1203 Orren Street, Northeast",
    location: "Los Angel, CA 90210",
    size: "2350 Square Feet",
    parking: "2 Garages",
    bedrooms: "22 Bedrooms",
    bathrooms: "11 Bathrooms",
    ownerName: "Tom Steven",
    lastActivity: "5 days ago",
    amount: "$3,142,000",
  },
  {
    id: 5,
    image: "house6.png",
    status: "For Sale",
    address: "1203 Orren Street, Northeast",
    location: "Los Angel, CA 90210",
    size: "2350 Square Feet",
    parking: "2 Garages",
    bedrooms: "22 Bedrooms",
    bathrooms: "11 Bathrooms",
    ownerName: "Tom Steven",
    lastActivity: "5 days ago",
    amount: "$2,384,000",
  }
];
export default FeaturedListingData;
