export const PropertiesData = [
  {
    id: 1,
    image: "property1.png",
    tag: "Singapore",
    price: "$300,000",
    address: "5232 North Carolina Ave. 21BC",
    country: "California, USA",
    bedroom: "4 beds",
    bathroom: "3 baths",
    agentImg: "people2.png",
    agentName: "William Hue",
    role: "Estate Agents",
  }, {
    id: 2,
    image: "property2.png",
    tag: "LOS Angels",
    price: "$350,000",
    address: "5232 North Carolina Ave. 21BC ",
    country: "Los Angels, USA",
    bedroom: "5 beds",
    bathroom: "3 baths",
    agentImg: "people2.png",
    agentName: "Adam Smith",
    role: "Estate Agents",
  },{
    id: 3,
    image: "property3.png",
    tag: "CALIFORNIA",
    price: "$500,000",
    address: "5232 North Carolina Ave. 21BC ",
    country: "Houston, USA",
    bedroom: "6 beds",
    bathroom: "4 baths",
    agentImg: "people3.png",
    agentName: "Adam Smith",
    role: "Estate Agents",
  },
];
